language: julia

os:
  - linux
  - osx

julia:
  - 1.0
  - 1.1
  - 1.2
  - nightly

matrix:
  allow_failures:
    - nightly

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/ # tags

notifications:
  email: false

jobs:
  include:
    - stage: Documentation
      julia: 1.1
      os: linux
      script:
        - julia --project=docs -e 'using Pkg; Pkg.instantiate(); Pkg.add(PackageSpec(path=pwd())); Pkg.build("HSL")'
        - julia --project=docs docs/make.jl
      after_success: skip

